Financial instruments transformer - Add endpoint to get all FIs APIURLs
Financial-Times/financial-instruments-transformer pull request #6
Opened 2017-01-06 08:30 UTC by iulianp26

2017-01-06 08:52 UTC, ghost requested changes
The transformer should have a __reload endpoint, to match all of the others.

2017-01-06 10:13 UTC, Nesze commented
Yeah, we'll add it (but for the record, I think most of the transformers lack that endpoint).

2017-01-06 12:25 UTC, tosan88 commented on handler_test.go
> +	if w.Code != 503 {
Can you please use `require.Equals` instead?

2017-01-06 12:25 UTC, tosan88 commented on service.go
> +		apiUrl := fis.baseUrl + uuid
I expect constructing the url is the reponsibility of the handler and not the service itself... Wouldn't be better just to return the uuids here? What is your opinion?

2017-01-06 12:26 UTC, tosan88 commented
@david-smith-ft @Nesze I also think that the lack of `__reload` is not a blocker for this change - I would see it in another PR...

2017-01-06 15:33 UTC, iulianp26 commented on service.go
> +		apiUrl := fis.baseUrl + uuid
Sounds ok to me. I'll make the change.

2017-01-09 08:57 UTC, tosan88 approved these changes

2017-01-09 09:56 UTC, Nesze commented
cc: @nwrigh

2017-01-09 09:56 UTC, ghost approved these changes

2017-01-09 12:07 UTC, merged